version: '3.8'
services:
  freehealth:
    build: .
    image: freehealth-connector:dev
    container_name: freehealth
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./config.json:/opt/freehealth/config.json:ro
      - ./logs:/opt/freehealth/logs

    restart: unless-stopped
 