on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  licenses_report:
    name: Generating licenses report
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Creating licenses report
        env:
          ORG_GRADLE_PROJECT_mavenReleasesRepository: https://maven.taktik.be/content/repositories/releases/'
          ORG_GRADLE_PROJECT_mavenRepository: https://maven.taktik.be/content/groups/public'
          ORG_GRADLE_PROJECT_mavenSnapshotsRepository: https://maven.taktik.be/content/repositories/snapshots/'
          ORG_GRADLE_PROJECT_repoUsername: ${{ secrets.REPO_USERNAME }}
          ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.REPO_PASSWORD }}
        run: ./gradlew generateLicenseReport -x build

      - name: Copy, rename, and remove header
        run: tail -n +2 ./build/reports/dependency-license/licenses.csv > ./${{ github.event.repository.name }}.csv

      - name: Setup Git
        run: |
          git config --global user.name "icure-dev"
          git config --global user.email "dev@icure.com"

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPO_DEPLOY_KEY }}"

      - name: Publish file to licenses-report
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git clone git@github.com:icure/licenses-report.git
          cd licenses-report
          mv ../${{ github.event.repository.name }}.csv ./java_kotlin/${{ github.event.repository.name }}.csv
          git add ./java_kotlin/${{ github.event.repository.name }}.csv
          STATUS=$(git status --porcelain)
          if [ -n "$STATUS" ]; then
            git commit -m "Update ${{ github.event.repository.name }}.csv"
            git push
          fi
